Fix dependencies
Before this, I got build errors complaining about undefined logrus symbols from
the docker package, e.g.

```
../../vendor/github.com/docker/docker/errdefs/http_helpers.go:103:21: undefined: logrus.Fields
```

I suspect this happened because the path for the logrus package has a casing
error, but this did not surface on case-insensitive filesystems.

In addition, I ran `go mod vendor` and `go mod tidy`, which added some
additional dependencies to go.mod.